language: rust
addons:
    apt:
      sources:
        - llvm-toolchain-precise-3.9
        - ubuntu-toolchain-r-test
      packages:
        - libclang-3.9-dev
        - llvm-3.9-dev
env:
  - LLVM_VERSION=3.9
rust:
  - stable
  - nightly
cache:
  directories:
    - $HOME/.cargo

before_install:
  -
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      if [ "${LLVM_VERSION}" != "devtools" ]; then
        brew update >/dev/null;
        brew install llvm3${LLVM_VERSION#3.};
      fi
    fi

before_script:
  -
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export LIBCLANG_PATH=/usr/lib/llvm-${LLVM_VERSION}/lib;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      if [ "${LLVM_VERSION}" = "devtools" ]; then
        export LIBCLANG_PATH=/Library/Developer/CommandLineTools/usr/lib;
      else
        export LIBCLANG_PATH=`brew --prefix llvm3${LLVM_VERSION#3.}`/lib/llvm-${LLVM_VERSION}/lib;
      fi
    fi
  - echo $LIBCLANG_PATH

script:
  - cargo build --verbose
  - make test
  - git add -A
  - git diff @
  - git diff-index --quiet HEAD

notifications:
  webhooks: http://build.servo.org:54856/travis
