language: rust
dist: xenial
os:
  - linux
rust:
  - stable
env:
  global:
    - CARGO_TARGET_DIR=/tmp/bindgen
script:
  - ./ci/test-book.sh
after_success:
  - test "$TRAVIS_PULL_REQUEST" == "false" &&
    test "$TRAVIS_BRANCH" == "master" &&
    ./ci/deploy-book.sh
