[package]
authors = [
  "Jyun-Yan You <jyyou.tw@gmail.com>",
  "Emilio Cobos Álvarez <ecoal95@gmail.com>",
  "The Servo project developers",
]
build = "build.rs"
description = "A binding generator for Rust"
homepage = "https://github.com/servo/rust-bindgen"
keywords = ["bindings", "ffi", "code-generation"]
license = "BSD-3-Clause"
name = "bindgen"
readme = "README.md"
repository = "https://github.com/servo/rust-bindgen"
version = "0.17.0"

[[bin]]
doc = false
name = "bindgen"

[build-dependencies]
quasi_codegen = "0.20"

[dependencies]
clang-sys = "0.8.0"
libc = "0.2"
log = "0.3"
env_logger = "0.3"
rustc-serialize = "0.3.19"
syntex_syntax = "0.44"
regex = "0.1"

[dependencies.aster]
features = ["with-syntex"]
version = "0.28"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.quasi]
features = ["with-syntex"]
version = "0.20"

[features]
static = []

[lib]
name = "bindgen"
path = "src/lib.rs"

[[test]]
name = "tests"
