[package]
authors = [
  "Jyun-Yan You <jyyou.tw@gmail.com>",
  "Emilio Cobos Álvarez <ecoal95@gmail.com>",
  "The Servo project developers",
]
build = "build.rs"
description = "A binding generator for Rust"
homepage = "https://github.com/servo/rust-bindgen"
keywords = ["bindings", "ffi", "code-generation"]
license = "BSD-3-Clause"
name = "libbindgen"
readme = "README.md"
repository = "https://github.com/servo/rust-bindgen"
version = "0.17.0"

[dev-dependencies]
diff = "0.1"
clap = "2"
shlex = "0.1"
tests_expectations = { path = "tests/expectations" }

[build-dependencies.quasi_codegen]
default-features = false
version = "0.25"

[dependencies]
aster = "0.33"
cexpr = "0.2"
cfg-if = "0.1.0"
clang-sys = "0.8.0"
lazy_static = "0.1.*"
libc = "0.2"
quasi = "0.25"
regex = "0.1"
rustc-serialize = "0.3.19"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.env_logger]
optional = true
version = "0.3"

[dependencies.log]
optional = true
version = "0.3"

[dependencies.syntex_syntax]
optional = true
version = "0.48"

[features]
default = ["logging", "syntex"]
llvm_stable = []
logging = ["env_logger", "log"]
static = []
syntex = ["syntex_syntax", "aster/with-syntex", "quasi/with-syntex", "quasi_codegen/with-syntex"]
# This feature only exists for CI -- don't use it!
_docs = []
