name: Deploy book

on:
  push:
    branches:
      - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test book
        run: |
          cargo install mdbook --root mdbook-install --vers "^0.2.1" --force
          ./mdbook-install/bin/mdbook build book
          ./mdbook-install/bin/mdbook test book

      - name: Deploy book
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: book/book
